name: Releases

on:
  release:
    types:
      - published

jobs:
  update-major-version-tag:
    name: Update major version tag
    permissions:
      contents: write
    uses: lubeso/github-workflow-update-major-version-tag@v0
    with:
      release_tag: ${{ github.event.release.tag_name }}
